apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-debug-worker
  labels:
    {{- include "daq-dranspose.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: control
  selector:
    app.kubernetes.io/component: debug-worker
    {{- include "daq-dranspose.selectorLabels" . | nindent 4 }}
