apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Namespace }}-reducer
  labels:
    {{- include "daq-dranspose.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10010
      name: workers
  selector:
    app.kubernetes.io/component: reducer
    {{- include "daq-dranspose.selectorLabels" $ | nindent 4 }}