apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    {{- include "daq-dranspose.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      name: redis
  selector:
    app.kubernetes.io/component: redis
    {{- include "daq-dranspose.selectorLabels" . | nindent 4 }}
