apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Namespace }}-controller
  labels:
    {{- include "daq-dranspose.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      name: controller
  selector:
    app.kubernetes.io/component: controller
    {{- include "daq-dranspose.selectorLabels" . | nindent 4 }}
