{{- range $module, $config := .Values.ingesters }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-ingester-{{ $module }}
  labels:
    app.kubernetes.io/componentgroup: ingesters
    app.kubernetes.io/component: ingester-{{ $module }}
    {{- include "daq-dranspose.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ingester-{{ $module }}
      app.kubernetes.io/componentgroup: ingesters
      {{- include "daq-dranspose.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: >-
          [{ "name": "purple-sriov-dhcp", "namespace": "daq-network",
          "interface": "purple0" }]
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: ingester-{{ $module }}
        app.kubernetes.io/componentgroup: ingesters
        {{- include "daq-dranspose.selectorLabels" $ | nindent 8 }}
    spec:
      securityContext:
        sysctls:
          - name: net.ipv4.tcp_wmem
            value: "4096 87380 16777216"
          - name: net.netfilter.nf_conntrack_tcp_timeout_close_wait
            value: "3600"
      containers:
      - name: {{ $.Chart.Name }}-ingester-{{ $module }}
        image: "harbor.maxiv.lu.se/daq/dranspose:main"
        command: ["dranspose"]
        args:
          - "ingester"
          - "--name"
          - "{{ $module }}"
          - "-c"
          - {{ $config.ingester_class | default "StreamingSingleIngester" | quote }}
          - "-u"
          - "{{ $config.connect_url }}"
        env: # purple cn2
          - name: BEAMLINE
            value: {{ $.Values.global.beamline | quote }}
          - name: INGESTER_URL
            value: "tcp://{{ $.Release.Namespace }}-ingester-{{ $module }}:10010"
          {{ if $.Values.global.dump_prefix }}
          - name: DUMP_PATH
            value: "{{ $.Values.global.dump_prefix }}{{ $module }}.pkls"
          {{ end }}
{{ include "daq-dranspose.extraEnv" $ | indent 10 }}
        imagePullPolicy: Always
        ports:
          - name: workers
            containerPort: 10010
            protocol: TCP
        resources:
          limits:
            daq.maxiv.lu.se/egress-bandwidth: 1k
            daq.maxiv.lu.se/ingress-bandwidth: 4k
            intel.com/mellanox_sriov_netdevice: '1'
          requests:
            daq.maxiv.lu.se/egress-bandwidth: 1k
            daq.maxiv.lu.se/ingress-bandwidth: 4k
            intel.com/mellanox_sriov_netdevice: '1'
      {{ if $.Values.global.dump_prefix }}
        volumeMounts:
          - name: daq-volume-staff
            mountPath: {{ printf "/data/staff/%s" $.Values.global.beamline }}
            readOnly: false
      volumes:
      - name: daq-volume-staff
        hostPath:
          path: {{ printf "/gpfs/offline1/staff/%s" $.Values.global.beamline }}
          type: Directory
      {{ end}}
{{ end }}
