{{- range $module, $config := .Values.ingesters }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Namespace }}-ingester-{{ $module }}
  labels:
    {{- include "daq-dranspose.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 10010
      name: workers
  selector:
    app.kubernetes.io/componentgroup: ingesters
    app.kubernetes.io/component: ingester-{{ $module }}
    {{- include "daq-dranspose.selectorLabels" $ | nindent 4 }}
{{ end }}