{{- range $module, $config := .Values.ingesters }}
{{ if $config.ingester_app }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Namespace }}-ingester-{{ $module }}-control
  labels:
    {{- include "daq-dranspose.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: control
  selector:
    app.kubernetes.io/componentgroup: ingesters
    app.kubernetes.io/component: ingester-{{ $module }}
    {{- include "daq-dranspose.selectorLabels" $ | nindent 4 }}
{{end}}
{{end}}